#develop
#server:
#    port: 8080
#test
server:
    port: 8080

spring:
    datasource:
#       develop
        name: test
        url: jdbc:mysql://rm-bp1k6dy03e1nj07q8o.mysql.rds.aliyuncs.com:3306/psmpkf
        username: psmp
        password: psmp2018
#        test
#        name: psmp
#        url: jdbc:mysql://41.220.1.153:3306/psmp
#        username: psmp
#        password: Psmp@2018
#        driverClassName: com.mysql.jdbc.Driver
        # \u4F7F\u7528druid\u6570\u636E\u6E90
#        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:  
      #数据库索引  
      database: 0  
      host: 127.0.0.1  
      port: 6379  
      password:  
      lettuce:  
        pool:  
          #最大连接数  
          max-active: 8  
          #最大阻塞等待时间(负数表示没限制)  
          max-wait: -1  
          #最大空闲  
          max-idle: 8  
          #最小空闲  
          min-idle: 0  
      #连接超时时间  
      timeout: 10000  

    thymeleaf:
      cache: false
      mode: LEGACYHTML5
#      prefix: classpath:/templates/
#      content-type: text/html
#      encoding: UTF-8
#     suffix: .html
#      check-template-location: true
#
    activiti:
        check-process-definitions: false


mybatis:
  mapper-locations: classpath*:mapper/**/*.xml